### ISSUE TITLE
TiSA for proteomics analysis

### ISSUE THREAD

**Issue by juniajvs** [Ylefol/TimeSeriesAnalysis#1]
Hello all,

Thank you so much for creating and sharing such a great package.
Would it be possible to use TiSA for proteomics analysis? Do I need to follow a binomial distribution to use your package or is it possible to apply it to other skewed distributions? Also would it be possible to input relative expression data? I am looking for a package that would allow me to analyze longitudinal samples from two distinct outcome groups, but that takes in account that the values I will be inputting are relative measurements compared to a detection curve.

**Comment by Ylefol** [comment]
Hello,

Unfortunately TiSA was never designed with proteomics in mind, it instead focused exclusively on transcriptomic data from either Microarray or RNAseq. 
My knowledge in proteomics is limited, but it appears that you may be able to use limma to process the proteomics data (thus creating an Elist), this could then be inputted to TiSA.
Looking at online sources, some individuals state that processing proteomics data with limma works, others state that the results are subpar, therefore that should be kept in mind if you choose to go this route.
As for the distributions, the differential gene expression components are relatively hard-coded into the pipeline. If you wish to do so, you could use the pipeline while editing the necessary functions to alter the distribution.

I'm unsure what you mean by relative expresison data. Would this be qPCR results? If so, I don't believe that the statistics within this pipeline will help on that end.

Best,
Yohan

**Comment by juniajvs** [comment]
Hello Yohan,

Thank you so much for your reply. I am using Olink proteomics, which enables you to select and combine target proteins in one biomarker panel with results reported in absolute quantification (pg/mL) and relative quantification (NPX). Since I have multiple batches, I've been using the NPX quantification since it is a more straightforward normalization. Unfortunately, it seems I won't be able to use the TiSA package for the analysis. I will create a mixed linear regression model and hopefully that should workout.

Best,
Junia
