### ISSUE TITLE
Error message computing PART clusters `hclust(dX, method = arg$linkage) :   must have n >= 2 objects to cluster`

### ISSUE THREAD

**Issue by macrobiotus** [Ylefol/TimeSeriesAnalysis#10]
Dear @Ylefol, 

Thank you for maintaining this package. As by my previously resolved issue i have now successfully "fed" my data into your code. 

Would you be able to shed some light on the error message:

```
 computing PART clusters
Error in hclust(dX, method = arg$linkage) : 
  must have n >= 2 objects to cluster 
```

I will of course attempt to dive into this deeper.

1.  Would this be related to there not being enough DEGs discovered between two contrasts (and could be solved e.g. by lowering some threshold)

2. Or is this the results of having to little sample replication (and can be resolved by excluding samples or timpoints (which would be undesirable to me)).

~~You may be able to replicate the issue, should you which to do so, by checking the files of the most recently closed issue ("9", I believe)~~

Kind regards, 

Paul

**Comment by Ylefol** [comment]
Hello @macrobiotus ,

It would appear to me that the issue would be the number of genes submitted to clustering, or the parameter called PART_min_clust which defined the smallest possible size for clusters. So if this were set to 50 but only 30 genes were submitted it may cause this error.
However I would first check that there are significant genes being submitted to the clustering. 

In the tutorial, this line of code 'signi_genes<-select_genes_with_l2fc(TS_object)' finds the number of genes submitted to the PART clustering. I would start by checking if this function identifies any genes. If not, the error may be upstream or in the parameters selected.

To be more specific, this function will look at the differential expression results, specifically at genes labelled as significant - with the standard being genes with an adjusted pvalue below 0.05 and an absolute log2foldchange greater than 1. With this gene list, the function then looks for any genes with an absolute log2foldchange greater or equal to the value given by the 'PART_l2fc' parameter. In the example I have the parameter set to 5 as the example data has some pretty strong signals, however in many datasets, particularly non cell line datasets, it may be best to set this parameter to 1.

My suggestion is therefore to check what your current parameters are and how many genes are being found with these, then adjust the parameters and check if that helps.

If this doesn't solve the issue, or other problems appear, please feel free to let me know and I'll help as best I can.

Best regards,
Yohan

**Comment by macrobiotus** [comment]
Dear Yohan, 

Thank you very much for your quick reply - I will test according to the information you provided.

Kind regards,

Paul

**Comment by macrobiotus** [comment]
This worked. Thank you.
