### ISSUE TITLE
How to obatin raw expression matrices for each PART cluster?

### ISSUE THREAD

**Issue by macrobiotus** [Ylefol/TimeSeriesAnalysis#12]
Dear Yohan, 

thank you for helping me running TISA twice before. I have a question regarding obtaining the raw expression values and genes for each of the clusters,  from PART clustering. 

For me TISA writes all results to a folder, and one subfolder looks as follows:

```
~/${some path}/tisa_results/PART_results$ tree
.
├── Ctraj.svg
├── PART_heat.svg
├── PART_heat_cmap.csv
├── PART_heat_data.csv
└── PART_heat_with_names.svg
```
We would like to have a list of [n], [m] [...] genes with raw expression values  which make up clsuters [C1] with [n] genes, [C2] with [m] genes, and so forth. 

Basically in the format e.g. for "C1"
`[ensembl id], [expression sample 1], [expression sample 2]`, etc. 

And the same for "C2" and "C3" and all others where available.

File `PART_heat_data.csv` appearsd close, but I am not sure if these are scaled expression values / z-scores, or raw expression data, and the information on the eclusters is lacking in the file. ) 

My instinct would be to use `PART_heat_data.csv` to isolate expression values . and `PART_heat_cmap.csv` to find group membership of genes per cluster (C1, C2, C3, ...) an so forth, read both into r, and get an expression matrix for each cluster C1, C2, C4 Cn+1 but this only works if  `PART_heat_data.csv` contains raw  expression values. 

How would I best go about getting expression matrices with genes, samplea and raw expression values for each PART cluster C1, C2?

I look forward to hearing from you.

Kind regards,

Paul

**Comment by Ylefol** [comment]
Hello,

Indeed the PART_heat_data file is not exactly what you're looking for. Specifically these are the values you see on the heatmap (Z-scores). To obtain the expression values you would need to use the 'exp_matrix' function and choose to extract either the raw or normalized (norm) matrix.

This little snippet of code should gather all the information in a single data frame. It could then be subsetted in whatever way necessary.

`my_matrix<-exp_matrix(TS_object,'norm') #Could use 'raw' instead
my_matrix<-my_matrix[row.names(TS_object@PART_results$part_data),]
PART_cmap<-TS_object@PART_results$cluster_map

merged_info<-merge(PART_cmap, my_matrix, by=0, all=TRUE)`

Best,
Yohan

**Comment by macrobiotus** [comment]
Dear Yohan,

Thank you for your reply, I appreciate it. I ended up reconstituting long data frames using the two required input tables, as well as the file `PART_heat_cmap.csv`.

Cheers,

Paul
