### ISSUE TITLE
plot_PCA_TS() fails when DE_type = temporal or conditional

### ISSUE THREAD

**Issue by maciejmotyka** [Ylefol/TimeSeriesAnalysis#5]
I'm trying to plot PCA for one of the temporal comparisons and it's failing because the function is extracting a non-existing `sub_dds` element from the DE results, which results in NULL being passed to the `vst()` function.
This will also fail when  `DE_type = "conditional"` for the same reason.

```
> plot_PCA_TS(ts_obj, DE_type='temporal', exp_name = "TP_2_vs_TP_1")

Error in if (nrow(object) < nsub) { : argument is of length zero
  2. vst(dds, blind = FALSE)
  1. plot_PCA_TS(ts_obj, DE_type = "temporal", exp_name = "TP_2_vs_TP_1")
```

See here:
https://github.com/Ylefol/TimeSeriesAnalysis/blob/e9710975dd40f7b976d3a3513c0a158d06a00675/R/DE_PART_results_functions.R#L487

My TS object has following elements for every contrast in `temporal` and `conditional`
```
> names(ts_obj@DE_results$temporal$TP_2_vs_TP_1)
[1] "DE_raw_data" "DE_sig_data"
```

**Comment by Ylefol** [comment]
Hello,

Apologies for that, some time ago I was messing around with the removal of the sub_dds but I couldn't manage to make the PCA work well without it. It seems that I left the relevant line commented out.

I've pushed the proper version to master. You will have to re-run the wrappers for both the conditional and temporal differential gene expression analyses.

**Comment by maciejmotyka** [comment]
That solves it, thanks!
