### ISSUE TITLE
Cannot succeed in running the example code

### ISSUE THREAD

**Issue by macrobiotus** [Ylefol/TimeSeriesAnalysis#8]
Dear Yohan, 

I am failing to get this code going, unfortunately, so that I cannot adjust it to my own data.

I have cloned the repository, installed all dependencies and am able to start running `TS_analysis.Rmd` both in Rstudio as well as over the command line.

Your code states:

```
# Path to count data and sample data respectively
# Not needed if using example data
my_path_data<-'~/A_Projects/EpiGen/R_Work_Folder/TimeSeriesAnalysis/data/PBMC/raw_counts_TS'
my_path_sample_dta<-'~/A_Projects/EpiGen/R_Work_Folder/TimeSeriesAnalysis/data/PBMC/sample_file.csv'
```
In my repository clone `/TimeSeriesAnalysis/data` does not contain either a `/PBMC/sample_file.csv` file, nor a `/PBMC/raw_counts_TS` as per screenshot.

I was under the impression that you code may catch these none-existences, and somehow reads in the many `.rda` files from `/TimeSeriesAnalysis/data/*rda`. But it doesn't appear to do this.

Commenting out the relvant lines like so:

```
# Path to count data and sample data respectively
# Not needed if using example data
# my_path_data<-'~/A_Projects/EpiGen/R_Work_Folder/TimeSeriesAnalysis/data/PBMC/raw_counts_TS'
# my_path_sample_dta<-'~/A_Projects/EpiGen/R_Work_Folder/TimeSeriesAnalysis/data/PBMC/sample_file.csv'
```
Makes the script fail with:

```
processing file: TS_analysis.Rmd
  |.......                                          |  14% [create_base_TS]    
Quitting from lines 117-130 [create_base_TS] (TS_analysis.Rmd)
Error:
! object 'my_path_sample_dta' not found
Backtrace:
 1. TimeSeriesAnalysis::add_experiment_data(...)
 2. TimeSeriesAnalysis::prep_sample_data(sample_dta_path, groups)
 3. utils::read.csv(path)
 4. utils::read.table(...)
                                                                                                               
Execution halted
```
How can I get the script running to start adjusting it to my own data? The best solution to me would be if there was example data provided in the repository itself - but clearly other have run this code so I must be missing something obvious.

I'd be looking forward to hearing from you in due course.

Kind ragards,

Paul
![Screenshot 2024-03-06 at 14 29 16](https://github.com/Ylefol/TimeSeriesAnalysis/assets/10920135/bcca5b44-9346-435c-972a-a7f07cd9eec8)

**Comment by Ylefol** [comment]
Hello,

Indeed the commented lines are misleading (it will be changed soon as an update is coming out in the next 2-3 weeks).

To get the files into your directory try using this function 'write_example_data_to_dir()'

This function will take the PBMC.rda and unpack it's content in the 'data' folder. The intent is that this will show the user the expected data format for the pipeline, making it easier to format their data according to the pipeline specifications.

Please let me know if this resolves the issue or if there other issues arise.

Best,
Yohan

**Comment by macrobiotus** [comment]
> To get the files into your directory try using this function 'write_example_data_to_dir()

Thank you now I can see in line 24

 ```
# COMMENT OUT IF NOT USING EXAMPLES
# write_example_data_to_dir('PBMC')`

```

Doing that:

 ```
# COMMENT OUT IF NOT USING EXAMPLES
 write_example_data_to_dir('PBMC')`

```
Issue resolved, thank you for your help.
